openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0
paths:
  #  This endpoint is not used, nor should it be.
  #  It is here because OpenApi enforces at least one endpoint to be here.
  #  This specification is used for the components section only.
  #
  /placeholder:
    get:
      operationId: non-used-placeholder-path
      responses:
        "200":
          description: OK
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errorResponseId:
          type: integer
        code:
          type:
            string
        message:
          type:
            string
        involvedProperties:
          type:
            string
    RecipeTagDTO:
      type: object
      required:
        - tag
      properties:
        tag:
          type: string
    AddRecipeTagRequestDTO:
      type: object
      required:
        - tag
      properties:
        tag:
          type: string
    GetRecipeTagsResponseDTO:
      type: object
      properties:
        tags:
          type: array
          items:
            $ref: '#/components/schemas/RecipeTagDTO'
    UpdateRecipeTagRequestDTO:
      type: object
      required:
        - oldTag
        - newTag
      properties:
        oldTag:
          type: string
        newTag:
          type: string
    DeleteRecipeTagRequestDTO:
      required:
        - tag
      type: object
      properties:
        tag:
          type: string
