openapi: 3.0.3
info:
  title: RecipeTag API
  description: RecipeTag API
  version: 1.0.0
paths:
  /rest/recipes/tags:
    post:
      tags:
        - recipe-tag-bd
      operationId: addRecipeTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/AddRecipeTagRequestDTO'
      responses:
        '201':
          description: Created
    get:
      tags:
        - recipe-tag-bd
      operationId: getRecipeTags
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: './components.yaml#/components/schemas/GetRecipeTagsResponseDTO'
    put:
      tags:
        - recipe-tag-bd
      operationId: updateRecipeTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/UpdateRecipeTagRequestDTO'
      responses:
        "200":
          description: OK
        '404':
          description: Not found
    delete:
      tags:
        - recipe-tag-bd
      operationId: deleteRecipeTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/DeleteRecipeTagRequestDTO'
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
